POST http://localhost:5000/calculate

Content-Type: application/json
X-API-Key: YOUR_KEY
{
    "chart_name": "Test Chart",
    "datetime": "1985-06-12 14:30:00",
    "location": "London, UK",
    "house_system": "placidus"
}
